#!/bin/bash

# Remove all shared memory segments
for id in $(ipcs -m | awk 'NR>3 {print $2}'); do
  echo "Removing shared memory segment ID: $id"
  ipcrm -m $id
done

# Remove all semaphore arrays
for id in $(ipcs -s | awk 'NR>3 {print $2}'); do
  echo "Removing semaphore array ID: $id"
  ipcrm -s $id
done

# Remove all message queues
for id in $(ipcs -q | awk 'NR>3 {print $2}'); do
  echo "Removing message queue ID: $id"
  ipcrm -q $id
done
